name: Docker Build

on:
  push:
    branches: [ "main", "dev" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract git information
        id: git-info
        run: |
          echo "commit-hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "commit-message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT
          echo "commit-date=$(git log -1 --pretty=format:'%ci')" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Debug metadata
        run: |
          echo "Generated tags: ${{ steps.meta.outputs.tags }}"
          echo "Branch: ${{ github.ref }}"
          echo "Is main branch: ${{ github.ref == 'refs/heads/main' }}"
          echo "Event: ${{ github.event_name }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_COMMIT_HASH=${{ steps.git-info.outputs.commit-hash }}
            GIT_COMMIT_MESSAGE=${{ steps.git-info.outputs.commit-message }}
            GIT_COMMIT_DATE=${{ steps.git-info.outputs.commit-date }}
            GIT_BRANCH=${{ steps.git-info.outputs.branch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 